from sqlalchemy import Column, Integer, String, Text, Boolean, DECIMAL, Date, DateTime, ARRAY, JSON, ForeignKey
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy import DateTime as TIMESTAMPTZ
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database import Base

class Empresa(Base):
    __tablename__ = "empresa"
    id = Column(Integer, primary_key=True)
    nombre = Column(String(200), nullable=False)
    rubro = Column(String(100))
    email = Column(String(200))
    telefono = Column(String(50))
    direccion = Column(Text)
    moneda = Column(String(10), default="USD")
    zona_horaria = Column(String(50), default="America/Argentina/Buenos_Aires")
    configuracion = Column(JSONB, default={})
    # Campos fiscales y bancarios
    cuit = Column(String(20))
    cbu = Column(String(50))
    alias_cbu = Column(String(50))
    banco = Column(String(100))
    # Plan y estado
    plan = Column(String(20), default="basico")
    estado = Column(String(20), default="activa")
    # Contacto y web
    contacto_nombre = Column(String(200))
    web = Column(String(500))
    instagram = Column(String(100))
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())

class Usuario(Base):
    __tablename__ = "usuarios"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    nombre = Column(String(200), nullable=False)
    email = Column(String(200), unique=True, nullable=False)
    password_hash = Column(String(200))
    rol = Column(String(20), default="operador")
    telegram_id = Column(String(50))
    activo = Column(Boolean, default=True)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())

class Cliente(Base):
    __tablename__ = "clientes"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    nombre = Column(String(200), nullable=False)
    empresa_nombre = Column(String(200))
    email = Column(String(200))
    telefono = Column(String(50))
    direccion = Column(Text)
    ciudad = Column(String(100))
    pais = Column(String(100), default="Argentina")
    estado = Column(String(20), default="activo")
    tipo = Column(String(20), default="empresa")
    valor_total = Column(DECIMAL(15,2), default=0)
    etiquetas = Column(Text)
    notas = Column(Text)
    fuente = Column(String(50))
    # Campos financieros
    cuit = Column(String(20))
    cbu = Column(String(25))
    alias_cbu = Column(String(50))
    banco = Column(String(100))
    contacto_nombre = Column(String(200))
    instagram = Column(String(100))
    web = Column(String(200))
    limite_credito = Column(DECIMAL(15,2), default=0)
    descuento_pct = Column(DECIMAL(5,2), default=0)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())
    interacciones = relationship("Interaccion", back_populates="cliente")

class Producto(Base):
    __tablename__ = "productos"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    categoria_id = Column(Integer, ForeignKey("categorias_productos.id"))
    nombre = Column(String(200), nullable=False)
    descripcion = Column(Text)
    tipo = Column(String(20), default="servicio")
    precio = Column(DECIMAL(15,2), nullable=False, default=0)
    precio_tipo = Column(String(20), default="unico")
    moneda = Column(String(10), default="USD")
    stock_actual = Column(Integer, default=0)
    stock_minimo = Column(Integer, default=0)
    control_stock = Column(Boolean, default=False)
    activo = Column(Boolean, default=True)
    codigo = Column(String(50))
    imagen_url = Column(String(500))
    # Catalogo publico
    visible_en_catalogo = Column(Boolean, default=False)
    destacado_en_catalogo = Column(Boolean, default=False)
    precio_oferta = Column(DECIMAL(15,2))
    orden_catalogo = Column(Integer, default=0)
    costo = Column(DECIMAL(15,2))
    descripcion_catalogo = Column(Text)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())

class CategoriaProducto(Base):
    __tablename__ = "categorias_productos"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    nombre = Column(String(100), nullable=False)
    descripcion = Column(Text)
    categoria_padre_id = Column(Integer, ForeignKey("categorias_productos.id"), nullable=True)
    orden = Column(Integer, default=0)
    activo = Column(Boolean, default=True)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    parent = relationship("CategoriaProducto", remote_side=[id])

class Proveedor(Base):
    __tablename__ = "proveedores"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    nombre = Column(String(200), nullable=False)
    contacto_nombre = Column(String(200))
    email = Column(String(200))
    telefono = Column(String(50))
    notas = Column(Text)
    activo = Column(Boolean, default=True)
    # Campos financieros
    cuit = Column(String(20))
    cbu = Column(String(25))
    alias_cbu = Column(String(50))
    banco = Column(String(100))
    condiciones_pago = Column(Text)
    descuento_pct = Column(DECIMAL(5,2), default=0)
    categoria = Column(String(100))
    web = Column(String(200))
    instagram = Column(String(100))
    created_at = Column(TIMESTAMPTZ, server_default=func.now())

class Factura(Base):
    __tablename__ = "facturas"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    cliente_id = Column(Integer, ForeignKey("clientes.id"))
    numero = Column(String(50))
    estado = Column(String(20), default="pendiente")
    fecha_emision = Column(Date)
    fecha_vencimiento = Column(Date)
    fecha_pago = Column(Date)
    subtotal = Column(DECIMAL(15,2), default=0)
    total = Column(DECIMAL(15,2), default=0)
    moneda = Column(String(10), default="USD")
    notas = Column(Text)
    metodo_pago = Column(String(50))
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())
    cliente = relationship("Cliente", foreign_keys=[cliente_id])
    items = relationship("ItemFactura", back_populates="factura")

class ItemFactura(Base):
    __tablename__ = "items_factura"
    id = Column(Integer, primary_key=True)
    factura_id = Column(Integer, ForeignKey("facturas.id"))
    producto_id = Column(Integer, ForeignKey("productos.id"))
    descripcion = Column(String(500), nullable=False)
    cantidad = Column(DECIMAL(10,2), default=1)
    precio_unitario = Column(DECIMAL(15,2), nullable=False)
    subtotal = Column(DECIMAL(15,2), nullable=False)
    factura = relationship("Factura", back_populates="items")

class Ticket(Base):
    __tablename__ = "tickets"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    cliente_id = Column(Integer, ForeignKey("clientes.id"))
    titulo = Column(String(500), nullable=False)
    descripcion = Column(Text)
    estado = Column(String(20), default="abierto")
    prioridad = Column(String(20), default="media")
    canal = Column(String(50), default="telegram")
    resolucion = Column(Text)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())

class Interaccion(Base):
    __tablename__ = "interacciones"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    cliente_id = Column(Integer, ForeignKey("clientes.id"))
    tipo = Column(String(50))
    descripcion = Column(Text, nullable=False)
    fecha = Column(TIMESTAMPTZ, server_default=func.now())
    cliente = relationship("Cliente", back_populates="interacciones")

# ============================================================
# MODELOS SALUD (Clínicas, diagnóstico por imágenes)
# ============================================================

class Paciente(Base):
    __tablename__ = "pacientes"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    nombre = Column(String(200), nullable=False)
    apellido = Column(String(200), nullable=False)
    dni = Column(String(20), nullable=False)
    fecha_nacimiento = Column(Date)
    sexo = Column(String(10))
    telefono = Column(String(50))
    email = Column(String(200))
    direccion = Column(Text)
    ciudad = Column(String(100))
    provincia = Column(String(100))
    obra_social = Column(String(200))
    numero_afiliado = Column(String(100))
    plan = Column(String(100))
    vigencia_afiliacion = Column(Date)
    activo = Column(Boolean, default=True)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())

class Medico(Base):
    __tablename__ = "medicos"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    usuario_id = Column(Integer, ForeignKey("usuarios.id"), nullable=True)
    nombre = Column(String(200), nullable=False)
    apellido = Column(String(200), nullable=False)
    matricula_provincial = Column(String(50))
    matricula_nacional = Column(String(50))
    especialidades = Column(ARRAY(String))
    duracion_turno_minutos = Column(Integer, default=30)
    horarios_atencion = Column(JSONB, default={})
    activo = Column(Boolean, default=True)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())

class Visita(Base):
    __tablename__ = "visitas"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    paciente_id = Column(Integer)
    paciente_nuevo_id = Column(Integer, ForeignKey("pacientes.id"))
    medico_id = Column(Integer, ForeignKey("medicos.id"), nullable=False)
    fecha_hora = Column(TIMESTAMPTZ, nullable=False)
    duracion_minutos = Column(Integer, default=30)
    estado = Column(String(50), default="pendiente")
    motivo_consulta = Column(Text)
    tipo_visita = Column(String(50), default="consulta")
    recordatorio_enviado = Column(Boolean, default=False)
    recordatorio_fecha = Column(TIMESTAMPTZ)
    cancelacion_motivo = Column(Text)
    fecha_cancelacion = Column(TIMESTAMPTZ)
    cancelado_por_usuario_id = Column(Integer, ForeignKey("usuarios.id"))
    reprogramado_a_visita_id = Column(Integer, ForeignKey("visitas.id"))
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())
    medico = relationship("Medico")

class HistoriaClinica(Base):
    __tablename__ = "historia_clinica"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    paciente_id = Column(Integer)
    paciente_nuevo_id = Column(Integer, ForeignKey("pacientes.id"))
    grupo_sanguineo = Column(String(10))
    alergias = Column(ARRAY(String), default=[])
    antecedentes_personales = Column(Text)
    antecedentes_familiares = Column(Text)
    medicacion_habitual = Column(ARRAY(String), default=[])
    cirugias_previas = Column(ARRAY(String), default=[])
    notas_adicionales = Column(Text)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())

class PracticaMedica(Base):
    __tablename__ = "practicas_medicas"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    atencion_medica_id = Column(Integer, nullable=False)  # NOT NULL en DB
    paciente_id = Column(Integer)
    paciente_nuevo_id = Column(Integer, ForeignKey("pacientes.id"))
    medico_id = Column(Integer, ForeignKey("medicos.id"), nullable=False)
    tipo_practica = Column(String(100))
    codigo_nomenclador = Column(String(50))
    descripcion_nomenclador = Column(Text)
    precio_practica = Column(DECIMAL(15,2), default=0)
    coseguro_paciente = Column(DECIMAL(15,2), default=0)
    cobertura_obra_social = Column(DECIMAL(15,2), default=0)
    estado_facturacion = Column(String(20), default="pendiente")
    fecha_facturacion = Column(Date)
    numero_factura = Column(String(50))
    requiere_autorizacion = Column(Boolean, default=False)
    numero_autorizacion = Column(String(50))
    fecha_autorizacion = Column(Date)
    observaciones = Column(Text)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())
    medico = relationship("Medico")

class NomencladorPractica(Base):
    __tablename__ = "nomenclador_practicas"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    codigo = Column(String(50))
    descripcion = Column(Text)
    tipo = Column(String(50))
    especialidad_requerida = Column(String(100))
    precio_particular = Column(DECIMAL(15,2), default=0)
    valor_modulo = Column(DECIMAL(10,2))
    duracion_minutos = Column(Integer)
    requiere_autorizacion = Column(Boolean, default=False)
    activo = Column(Boolean, default=True)

class AtencionMedica(Base):
    __tablename__ = "atenciones_medicas"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    visita_id = Column(Integer)
    paciente_id = Column(Integer)
    paciente_nuevo_id = Column(Integer, ForeignKey("pacientes.id"))
    medico_id = Column(Integer, ForeignKey("medicos.id"))
    fecha_hora_inicio = Column(TIMESTAMPTZ)
    fecha_hora_fin = Column(TIMESTAMPTZ)
    estado = Column(String(20))
    anamnesis = Column(Text)
    examen_fisico = Column(Text)
    diagnostico = Column(Text)
    plan_tratamiento = Column(Text)
    observaciones = Column(Text)
    presion_arterial = Column(String(20))
    frecuencia_cardiaca = Column(Integer)
    frecuencia_respiratoria = Column(Integer)
    temperatura = Column(DECIMAL(5,2))
    saturacion_oxigeno = Column(Integer)
    peso = Column(DECIMAL(5,2))
    altura = Column(DECIMAL(4,2))
    imc = Column(DECIMAL(5,2))
    evolucion = Column(Text)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    updated_at = Column(TIMESTAMPTZ, server_default=func.now())
    medico = relationship("Medico", foreign_keys=[medico_id])

class Receta(Base):
    __tablename__ = "recetas"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    atencion_medica_id = Column(Integer, ForeignKey("atenciones_medicas.id"), nullable=False)
    paciente_id = Column(Integer)
    paciente_nuevo_id = Column(Integer, ForeignKey("pacientes.id"))
    medico_id = Column(Integer, ForeignKey("medicos.id"))
    medicamentos = Column(JSONB, nullable=False)
    indicaciones = Column(Text)
    valida_hasta = Column(Date)
    archivo_pdf_url = Column(Text)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
    medico = relationship("Medico")

class EstudioAdjunto(Base):
    __tablename__ = "estudios_adjuntos"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    paciente_id = Column(Integer)
    paciente_nuevo_id = Column(Integer, ForeignKey("pacientes.id"))
    tipo_estudio = Column(String(100))
    descripcion = Column(Text)
    fecha_estudio = Column(Date)
    archivo_nombre = Column(String(255))
    archivo_url = Column(Text)
    archivo_tipo = Column(String(50))
    archivo_tamano_bytes = Column(Integer)
    consulta_id = Column(Integer, ForeignKey("visitas.id"))
    subido_por_usuario_id = Column(Integer, ForeignKey("usuarios.id"))
    created_at = Column(TIMESTAMPTZ, server_default=func.now())

class NotificacionProgramada(Base):
    __tablename__ = "notificaciones_programadas"
    id = Column(Integer, primary_key=True)
    empresa_id = Column(Integer, ForeignKey("empresa.id"))
    tipo = Column(String(50))
    referencia_tabla = Column(String(50))
    referencia_id = Column(Integer)
    mensaje = Column(Text)
    canal = Column(String(50))
    programado_para = Column(TIMESTAMPTZ)
    enviado = Column(Boolean, default=False)
    enviado_at = Column(TIMESTAMPTZ)
    created_at = Column(TIMESTAMPTZ, server_default=func.now())
